name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    name: Test on Node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.node_version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node_version}}
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: node_modules
          key: ${{runner.os}}-${{matrix.node_version}}-yarn-${{hashFiles('yarn.lock')}}
      - name: Install Dependencies
        run: yarn
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - name: Test
        run: yarn test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install Dependencies
        run: yarn
      - name: Lint
        run: yarn prettier:check && yarn lint

  type-check:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install Dependencies
        run: yarn
      - name: Lint
        run: yarn type-check
